# Generated by Django 3.0.8 on 2021-03-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='subheader',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
